spring.jms.servicebus.connection-string=connection-string
spring.jms.pub-sub-domain=true
spring.jms.servicebus.pricing-tier=standard
spring.jms.listener.receive-timeout=60000
spring.jms.servicebus.enabled= true